### ISSUE TITLE
[Model] Lab model has different scale from headsets

### ISSUE THREAD

**Issue by snowymo** [futurerealitylab/immersive-presentation#10]
**Describe the bug**
Currently, lab fbx was converted to gltf model via https://github.com/facebookincubator/FBX2glTF and the output gltf model is too small compared to the existing headset gltf model.

**To Reproduce**
Load lab gltf model directly.

**Expected behavior**
A correct scale.

**Screenshots**
![image](https://user-images.githubusercontent.com/10137769/116731018-32b89900-a9b7-11eb-8946-66d3aa7b7ecc.png)

**Desktop (please complete the following information):**

- Browser [chrome]

**Additional context**
We need to find a way to convert other formats to gltf model for metaroom to use.
We also need to figure out the unit in webxr, unity, unreal, etc.

@cdefanti Feel free to add any description for progress control.

**Comment by cdefanti** [comment]
This should be fixed in the latest push to 60fifth branch. Scaled up by a factor of 100 in Blender, and it seems to be the right size.

**Comment by snowymo** [comment]
Please copy the commit link here and even attach a new screenshot if possible. I'd love to help integrate into main branch so this issue is finalized.

**Comment by cdefanti** [comment]
Sure thing: https://github.com/futurerealitylab/immersive-presentation/commit/31e5c5ea5037b0716acac354188e2f789cbc9b3c
Here are a couple screenshots.
![image](https://user-images.githubusercontent.com/6417740/116916566-5b809e80-ac02-11eb-8c72-0fb65bf64533.png)
![image](https://user-images.githubusercontent.com/6417740/116916619-6dfad800-ac02-11eb-902a-8cb357a18abe.png)
The textures, particularly the floor texture, is a bit blurry, so we might want a rescan of it at some point. Additionally, we may want to introduce more lights into the scene to have the ceilings and office rooms better lit.
However, I think this is ready to go. The main reason why I haven't yet merged into main is that I wanted to check with the team if we should have this model be the default for the scene (replacing the futuristic lab model), or if this should be loaded in with a different button press. Otherwise, it should merge in with few to no conflicts.

**Comment by snowymo** [comment]
Excellent!

@kenperlin Please take a look at the screenshot. Shall we rescan the lab, or use the lab model for our environment setup in main branch, or?

**Comment by kenperlin** [comment]
We should use this as the default. We can hold off on rescanning.

**Comment by snowymo** [comment]
Great!

@cdefanti please open a pull request when you are ready and specify me or anyone else as the reviewer.

Any clue for my confusion here?
**Additional context**
We need to find a way to convert other formats to gltf model for metaroom to use.
We also need to figure out the unit in webxr, unity, unreal, etc.

**Comment by snowymo** [comment]
@cdefanti Shall we try that now so maybe it could be ready for tomorrow's meeting.

Thanks!

**Comment by cdefanti** [comment]
Here you go: https://github.com/futurerealitylab/immersive-presentation/pull/17
Looks like it can't auto-merge, but there is only 1 line of conflict, so it should be easy to manually fix.

**Comment by snowymo** [comment]
Currently, scale 100x in blender and re-export to gltf.
